// Preguntas de autoevaluación de la serie "De Copilot a Claude", por idioma y por post.
// Regla al escribirlas: todas las opciones de una pregunta tienen un largo parecido y son plausibles;
// la correcta no debe ser la más larga ni la más detallada. La página mezcla el orden al mostrarlas.
export type Quiz = { q: string; o: string[]; a: number; w: string }[]
export type QuizSet = Record<string, Quiz>

export const quizzes: Record<"es" | "en", QuizSet> = {
  es: {
    c: [
      { q: "Necesitas que alguien revise 30 archivos y te devuelva solo los hallazgos, sin llenar tu sesión. ¿Qué usas?", o: ["Un subagente con herramientas de solo lectura", "Una skill con allowed-tools limitadas a solo lectura", "Una regla con paths sobre esos archivos"], a: 0, w: "El subagente trabaja en su propio contexto y solo devuelve el resultado. Una skill se ejecuta dentro de tu sesión, así que todo lo que lea ocupa tu contexto." },
      { q: "El release tiene 7 pasos que siempre se hacen igual y no quieres que Claude lo lance por su cuenta. ¿Qué configuras?", o: ["Un subagente con permissionMode: plan", "Una skill con disable-model-invocation", "Una skill con user-invocable: false en el frontmatter"], a: 1, w: "disable-model-invocation deja la skill solo para /nombre. user-invocable: false hace lo contrario: solo Claude puede usarla." },
      { q: "Buscar dónde se usa una clase, muchas veces al día. ¿Qué combinación rinde mejor?", o: ["Opus 5 con esfuerzo medio en la sesión", "Sonnet 5 con esfuerzo alto directamente en la sesión", "Haiku 4.5 con esfuerzo bajo en un subagente"], a: 2, w: "Es trabajo mecánico y repetido: un modelo rápido con poco esfuerzo, aislado en un subagente para no llenar tu contexto." },
      { q: "Tu equipo habla español. ¿Qué conviene escribir en inglés para ahorrar tokens?", o: ["CLAUDE.md y las descripciones de skills", "Los prompts que escribes cada día", "Las respuestas que Claude te da en cada turno"], a: 0, w: "CLAUDE.md, reglas y descripciones se cargan en cada sesión o cada turno. En los prompts el sobrecosto real es de ~5%, porque son una parte pequeña del contexto." },
    ],
    s1: [
      { q: "Quieres que todo el equipo consulte los ADRs y el contrato OpenAPI desde el chat de claude.ai. ¿Dónde los pones?", o: ["En el CLAUDE.md del repositorio", "En el conocimiento de un Project", "En la memoria personal de cada integrante"], a: 1, w: "El Project comparte conocimiento e instrucciones en claude.ai. CLAUDE.md lo lee Claude Code dentro del repo, no el chat." },
      { q: "En un plan Team, ¿qué conversaciones se usan para entrenar modelos por defecto?", o: ["Las que el admin no marca como privadas", "Solo las de chats que no son incógnito", "Ninguna, salvo las que reciben pulgar"], a: 2, w: "Los planes comerciales no se usan para entrenar por defecto. El feedback con pulgar arriba o abajo sí conserva esa conversación; el admin puede apagarlo con \"Rate chats\"." },
      { q: "Una pregunta rápida sobre la sintaxis de LINQ o de un tipo de TypeScript. ¿Qué configuración?", o: ["Sonnet 5 con esfuerzo bajo", "Fable 5.1 con esfuerzo bajo", "Opus 5 con Research activo"], a: 0, w: "Respuesta conocida: un modelo rápido y poco esfuerzo. Fable con esfuerzo bajo funciona, pero gasta más cuota sin mejorar la respuesta." },
    ],
    s2: [
      { q: "¿Qué recibe Claude Code con el paquete de handoff de Claude Design?", o: ["Una exportación PNG de cada pantalla diseñada", "El trabajo de diseño con su estructura", "Un archivo .fig listo para abrir"], a: 1, w: "El handoff lleva la información del diseño para implementar sobre ella, no una imagen de la que haya que adivinar la estructura." },
      { q: "En un plan Enterprise nadie ve Claude Design. ¿Causa más probable?", o: ["Hay que instalar el plugin de Design", "Enterprise solo lo incluye en asientos Premium", "Viene apagado hasta que un Owner lo activa"], a: 2, w: "En Enterprise viene desactivado por defecto (Organization settings → Artifacts). En Pro, Max y Team viene activo." },
      { q: "¿Qué hace /design-sync en Claude Code?", o: ["Sube un design system de React a Design", "Descarga los diseños a una carpeta del repo", "Sincroniza Figma con el repo en GitHub"], a: 0, w: "Lleva el design system del código a Claude Design. /design-login autoriza el acceso." },
    ],
    s3: [
      { q: "Vas a cambiar 8 archivos en un módulo que no conoces. ¿Cómo empiezas?", o: ["En acceptEdits, pidiendo cambios pequeños", "En plan, aprobando un plan antes de editar", "En default, aprobando a mano cada una de las ediciones"], a: 1, w: "Plan explora sin editar, y corriges el plan antes de que haya código que deshacer. Aprobar edición por edición no te dice si el enfoque es el correcto." },
      { q: "Terminaste una feature y vas a investigar un bug sin relación. ¿Qué haces?", o: ["/compact para liberar espacio", "/rewind al inicio de la sesión", "/clear para empezar de cero"], a: 2, w: "/clear entre tareas no relacionadas. /compact es para seguir con la misma tarea; /rewind además desharía tu código." },
      { q: "¿Cuál de estos prompts funciona mejor?", o: ["\"Arregla #482; antes, un test que lo reproduzca\"", "\"Arregla #482 y asegúrate de que funcione bien\"", "\"Revisa RefundService y mejora lo que haga falta\""], a: 0, w: "Tiene alcance y un criterio de éxito verificable: un test que falla y después pasa. \"Que funcione bien\" no se puede comprobar." },
      { q: "Aprobaste un plan. Quieres que Claude edite sin preguntar, pero que pida permiso antes de instalar paquetes. ¿Qué modo?", o: ["auto", "acceptEdits", "dontAsk", "bypassPermissions"], a: 1, w: "acceptEdits acepta ediciones sin preguntar; los demás comandos siguen las reglas de permisos. auto decidiría solo, y dontAsk rechazaría la instalación sin preguntarte." },
      { q: "A mitad de una tarea te surge una duda que no tiene que ver con el cambio. ¿Qué usas?", o: ["/branch", "/compact", "/btw"], a: 2, w: "/btw responde sin dejar la pregunta en el historial. /branch crea otra línea de conversación, útil para probar otra solución, no para una duda." },
      { q: "Vas a correr Claude en un pipeline de CI donde nadie puede aprobar nada. ¿Qué modo?", o: ["dontAsk con --allowedTools", "auto con --allowedTools y --max-turns", "plan con --max-turns"], a: 0, w: "dontAsk rechaza todo lo que requeriría preguntar y solo corre lo aprobado. auto podría aprobar acciones que no esperabas en un entorno sin supervisión." },
    ],
    s4: [
      { q: "User settings tiene allow \"Bash(git push *)\" y el repo tiene deny \"Bash(git push *)\". ¿Qué pasa?", o: ["Gana el allow, porque es personal", "Gana el deny, en cualquier capa", "Claude pregunta, porque chocan"], a: 1, w: "Se evalúa deny → ask → allow, y un deny en cualquier capa no se puede anular con un allow." },
      { q: "Quieres reglas que solo apliquen a los archivos de tests. ¿Dónde van?", o: ["En CLAUDE.md, bajo un título de tests", "En una skill que se llame testing", "En .claude/rules/ con paths"], a: 2, w: "Las reglas con paths solo se cargan cuando Claude lee archivos que coinciden, así no gastan contexto el resto del tiempo." },
      { q: "¿Dónde pones la URL de tu base de datos de pruebas personal para este repo?", o: ["En CLAUDE.local.md", "En .claude/settings.json", "En ~/.claude/CLAUDE.md"], a: 0, w: "CLAUDE.local.md es personal por proyecto y va en .gitignore. ~/.claude/CLAUDE.md aplicaría a todos tus repos." },
    ],
    s5: [
      { q: "El código debe formatearse SIEMPRE después de cada edición. ¿Qué usas?", o: ["Una regla en CLAUDE.md", "Un hook PostToolUse", "Una skill de formato"], a: 1, w: "Los hooks se ejecutan siempre. CLAUDE.md y las skills son instrucciones que Claude intenta seguir, sin garantía." },
      { q: "Un hook PreToolUse termina con código 2 y escribe un mensaje en stderr. ¿Resultado?", o: ["Se muestra un aviso en la terminal y la acción continúa", "Claude Code pide permiso al usuario", "La acción se bloquea y Claude lee el motivo"], a: 2, w: "Exit 2 bloquea y el stderr llega a Claude como motivo. Otros códigos distintos de 0 son errores que no bloquean." },
      { q: "¿Para qué sirve revisar stop_hook_active en un hook de Stop?", o: ["No forzar a continuar dos veces seguidas", "Saber si el usuario detuvo a Claude con la tecla Esc", "Saber si el hook está habilitado"], a: 0, w: "Si ya obligaste a Claude a continuar una vez, deja que termine. Así evitas un bucle." },
      { q: "Una skill de deploy nunca debe ejecutarse por iniciativa de Claude. ¿Qué campo usas?", o: ["user-invocable: false", "context: fork", "disable-model-invocation: true", "allowed-tools sin herramientas de deploy"], a: 2, w: "disable-model-invocation: true deja la skill solo para /nombre. user-invocable: false es lo opuesto: solo Claude puede usarla." },
    ],
    s6: [
      { q: "Todo el equipo debe tener el mismo servidor MCP al clonar el repo. ¿Qué scope?", o: ["local", "user", "managed", "project"], a: 3, w: "El scope project guarda la configuración en .mcp.json, que se sube a git. local y user viven en tu máquina, y managed lo define el admin para toda la organización." },
      { q: "¿Cómo distribuyes skills, hooks y subagentes a 12 repositorios sin copiar archivos?", o: ["Un plugin en un marketplace interno", "Un Project compartido en claude.ai", "Un CLAUDE.md común importado con @ en cada repo"], a: 0, w: "Los plugins empaquetan skills, agentes, hooks y MCP; con extraKnownMarketplaces y enabledPlugins se activan en cada repo." },
      { q: "¿Qué configuración no puede anular ningún desarrollador?", o: [".claude/settings.local.json", "Los managed settings", "El flag --allowedTools"], a: 1, w: "Los managed settings tienen la máxima prioridad, incluso sobre los flags de la línea de comandos." },
    ],
  },
  en: {
    c: [
      { q: "You need someone to review 30 files and return only the findings, without filling your session. What do you use?", o: ["A subagent with read-only tools", "A skill with read-only allowed-tools", "A rule with paths for those files"], a: 0, w: "The subagent works in its own context and only returns the result. A skill runs inside your session, so everything it reads takes up your context." },
      { q: "The release has 7 steps done the same way every time, and you don't want Claude starting it on its own. What do you set up?", o: ["A subagent with permissionMode: plan", "A skill with disable-model-invocation", "A skill with user-invocable: false in its frontmatter"], a: 1, w: "disable-model-invocation leaves the skill for /name only. user-invocable: false does the opposite: only Claude can use it." },
      { q: "Finding where a class is used, many times a day. Which combination works best?", o: ["Opus 5 on medium effort in the session", "Sonnet 5 on high effort in the session", "Haiku 4.5 on low effort in a subagent"], a: 2, w: "It's mechanical, repeated work: a fast model with little effort, isolated in a subagent so it doesn't fill your context." },
      { q: "Your team speaks Spanish. What's worth writing in English to save tokens?", o: ["CLAUDE.md and skill descriptions", "The prompts you write every day", "The answers Claude gives you each turn"], a: 0, w: "CLAUDE.md, rules and descriptions load in every session or turn. In prompts the real overhead is ~5%, because they're a small part of the context." },
    ],
    s1: [
      { q: "You want the whole team to query the ADRs and OpenAPI contract from claude.ai chat. Where do you put them?", o: ["In the repository's CLAUDE.md", "In a Project's knowledge", "In each person's memory"], a: 1, w: "A Project shares knowledge and instructions in claude.ai. CLAUDE.md is read by Claude Code inside the repo, not by chat." },
      { q: "On a Team plan, which conversations are used to train models by default?", o: ["Those the admin doesn't mark as private in settings", "Only chats that aren't incognito", "None, except those that get a thumbs rating"], a: 2, w: "Commercial plans aren't used for training by default. Thumbs up/down feedback does retain that conversation; the admin can turn it off with \"Rate chats\"." },
      { q: "A quick question about LINQ syntax or a TypeScript type. Which setup?", o: ["Sonnet 5 on low effort", "Fable 5.1 on low effort", "Opus 5 with Research on"], a: 0, w: "A known answer: a fast model and little effort. Fable on low effort works, but uses more quota without improving the answer." },
    ],
    s2: [
      { q: "What does Claude Code receive in the Claude Design handoff package?", o: ["A PNG export of every designed screen", "The design work with its structure", "A .fig file ready to open"], a: 1, w: "The handoff carries the design information to implement on top of, not an image whose structure has to be guessed." },
      { q: "On an Enterprise plan nobody can see Claude Design. Most likely cause?", o: ["You need to install the Design plugin", "Enterprise only includes it on Premium seats", "It ships off until an Owner turns it on"], a: 2, w: "On Enterprise it's off by default (Organization settings → Artifacts). On Pro, Max and Team it's on." },
      { q: "What does /design-sync do in Claude Code?", o: ["Uploads a React design system to Design", "Downloads designs into a repo folder", "Syncs your Figma files with the repo on GitHub"], a: 0, w: "It takes the design system from the code to Claude Design. /design-login authorizes access." },
    ],
    s3: [
      { q: "You're about to change 8 files in a module you don't know. How do you start?", o: ["In acceptEdits, asking for small changes", "In plan, approving a plan before editing", "In default, approving each edit by hand"], a: 1, w: "Plan explores without editing, and you correct the plan before there's any code to undo. Approving edit by edit doesn't tell you whether the approach is right." },
      { q: "You finished a feature and are about to investigate an unrelated bug. What do you do?", o: ["/compact to free up space", "/rewind to the session start", "/clear to start from scratch"], a: 2, w: "/clear between unrelated tasks. /compact is for continuing the same task; /rewind would also undo your code." },
      { q: "Which of these prompts works best?", o: ["\"Fix #482; first, a test that reproduces it\"", "\"Fix #482 and make sure it works properly\"", "\"Review RefundService and improve what's needed\""], a: 0, w: "It has scope and a verifiable success criterion: a test that fails and then passes. \"Works properly\" can't be checked." },
      { q: "You approved a plan. You want Claude to edit without asking, but ask before installing packages. Which mode?", o: ["auto", "acceptEdits", "dontAsk", "bypassPermissions"], a: 1, w: "acceptEdits accepts edits without asking; other commands still follow the permission rules. auto would decide on its own, and dontAsk would deny the install without asking you." },
      { q: "Mid-task, you have a question unrelated to the change. What do you use?", o: ["/branch", "/compact", "/btw"], a: 2, w: "/btw answers without leaving the question in the history. /branch creates another line of conversation, useful for trying another solution, not for a question." },
      { q: "You'll run Claude in a CI pipeline where nobody can approve anything. Which mode?", o: ["dontAsk with --allowedTools", "auto with --allowedTools and --max-turns", "plan with --max-turns"], a: 0, w: "dontAsk denies anything that would require asking and only runs what's approved. auto could approve actions you didn't expect in an unsupervised environment." },
    ],
    s4: [
      { q: "User settings have allow \"Bash(git push *)\" and the repo has deny \"Bash(git push *)\". What happens?", o: ["The allow wins, since it's personal", "The deny wins, in any layer", "Claude asks, since they conflict"], a: 1, w: "Evaluation goes deny → ask → allow, and a deny in any layer can't be overridden by an allow." },
      { q: "You want rules that apply only to test files. Where do they go?", o: ["In CLAUDE.md, under a tests heading", "In a skill called testing", "In .claude/rules/ with paths"], a: 2, w: "Rules with paths only load when Claude reads matching files, so they don't use context the rest of the time." },
      { q: "Where do you put your personal test database URL for this repo?", o: ["In CLAUDE.local.md", "In .claude/settings.json", "In ~/.claude/CLAUDE.md"], a: 0, w: "CLAUDE.local.md is personal per project and goes in .gitignore. ~/.claude/CLAUDE.md would apply to all your repos." },
    ],
    s5: [
      { q: "Code must ALWAYS be formatted after every edit. What do you use?", o: ["A rule in CLAUDE.md", "A PostToolUse hook", "A formatting skill"], a: 1, w: "Hooks always run. CLAUDE.md and skills are instructions Claude tries to follow, with no guarantee." },
      { q: "A PreToolUse hook exits with code 2 and writes a message to stderr. Result?", o: ["A warning shows in the terminal and the action runs", "Claude Code asks the user for permission", "The action is blocked and Claude reads why"], a: 2, w: "Exit 2 blocks and stderr reaches Claude as the reason. Other non-zero codes are non-blocking errors." },
      { q: "What is checking stop_hook_active in a Stop hook for?", o: ["Not forcing it to continue twice in a row", "Knowing if the user stopped Claude with Esc", "Knowing if the hook is enabled"], a: 0, w: "If you already forced Claude to continue once, let it finish. That avoids a loop." },
      { q: "A deploy skill must never run on Claude's own initiative. Which field?", o: ["user-invocable: false", "context: fork", "disable-model-invocation: true", "allowed-tools without any deploy tools"], a: 2, w: "disable-model-invocation: true leaves the skill for /name only. user-invocable: false is the opposite: only Claude can use it." },
    ],
    s6: [
      { q: "The whole team should get the same MCP server when they clone the repo. Which scope?", o: ["local", "user", "managed", "project"], a: 3, w: "The project scope stores the configuration in .mcp.json, which goes into git. local and user live on your machine, and managed is set by the admin for the whole organization." },
      { q: "How do you distribute skills, hooks and subagents to 12 repositories without copying files?", o: ["A plugin in an internal marketplace", "A shared Project in claude.ai", "A shared CLAUDE.md imported with @ in each repo"], a: 0, w: "Plugins bundle skills, agents, hooks and MCP; extraKnownMarketplaces and enabledPlugins turn them on in each repo." },
      { q: "Which configuration can no developer override?", o: [".claude/settings.local.json", "Managed settings", "The --allowedTools flag"], a: 1, w: "Managed settings have the highest priority, even over command-line flags." },
    ],
  },
}
